{{- /* Validate .Values.floatingIP is a parseable IPv4 / IPv6 literal
       on controlplane renders. Shared by both the v1.12 multi-doc
       and the v1.11 legacy network defines so the same fail-fast
       happens regardless of the rendered Talos version. Calling
       template must pass the chart context as the dot — the partial
       reads .Values.floatingIP and .MachineType.

       The Sprig serialisation of nil is the literal string "<nil>",
       and an unset string is "". Both mean "operator did not supply
       a value" and skip the check. Numeric YAML scalars (operator
       writes `floatingIP: 192168` without quotes), bool false /
       numeric 0, and any other shape stringifies via toString and
       reaches ipIsValid — the friendly fail names the bad value
       with %q. */ -}}
{{- define "talm.validate_floatingIP" -}}
{{- $fipStr := .Values.floatingIP | toString -}}
{{- $fipIsSet := and (ne $fipStr "") (ne $fipStr "<nil>") -}}
{{- if and $fipIsSet (eq .MachineType "controlplane") -}}
{{- if not (ipIsValid $fipStr) -}}
{{- fail (printf "talm: floatingIP %q is not a valid IPv4 / IPv6 literal. Edit values.yaml and re-run." $fipStr) -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "talm.discovered.system_disk_name" }}
{{- $systemDisk := (lookup "systemdisk" "" "system-disk") }}
{{- if $systemDisk }}
{{- $systemDisk.spec.devPath }}
{{- else }}
{{- $disk := "/dev/sda" }}
{{- range (lookup "disks" "" "").items }}
{{- if or .spec.wwid .spec.model }}
{{- $disk = .spec.dev_path }}
{{- break }}
{{- end }}
{{- end }}
{{- $disk }}
{{- end }}
{{- end }}

{{- define "talm.discovered.machinetype" }}
{{- (lookup "machinetype" "" "machine-type").spec }}
{{- end }}

{{- /*
  talm.discovered.hostname returns the live node's hostname when it looks
  user-set, and falls back to a synthetic talos-XXXXX placeholder otherwise.

  Boot-to-talos and Talos's own pre-config state can leave a node with a
  transient placeholder hostname — `rescue` (Hetzner rescue OS), `talos`
  (Talos default before any config), `localhost` and `localhost.localdomain`
  (kernel and initramfs defaults).
  Propagating those names into the rendered template would let
  `talm template -I` write them back into the node body, where they read
  as "applied state" to the user; the next apply replays the placeholder,
  discovery returns it, and the loop never resolves to the user's intended
  per-node hostname.

  Filtering well-known transient names and falling through to the
  address-derived placeholder gives the user a visibly synthetic
  `hostname: "talos-abcde"` in the autogenerated body, signalling
  "replace me with a real per-node value".

  The match is case-insensitive: Sprig's `has` is exact-match, but some
  PXE/DHCP servers hand out title-case forms (`Localhost`) or all-caps
  (`TALOS`, `RESCUE`), and the trap-loop is identical for those. Lower-
  casing $name before the comparison covers them with no behavior change
  for the canonical lowercase forms.
*/ -}}
{{- define "talm.discovered.hostname" }}
{{- $hostname := lookup "hostname" "" "hostname" }}
{{- $name := "" }}
{{- if $hostname }}
{{- $name = $hostname.spec.hostname }}
{{- end }}
{{- if and $name (not (has (lower $name) (list "rescue" "talos" "localhost" "localhost.localdomain"))) }}
{{- $name }}
{{- else }}
{{- printf "talos-%s" (include "talm.discovered.default_addresses_by_gateway" . | sha256sum | trunc 5) }}
{{- end }}
{{- end }}

{{- define "talm.discovered.disks_info" }}
# -- Discovered disks:
{{- range (lookup "disks" "" "").items }}
{{- if or .spec.wwid .spec.model }}
# {{ .spec.dev_path }}:
#    model: {{ .spec.model }}
#    serial: {{ .spec.serial }}
#    wwid: {{ .spec.wwid }}
#    size: {{ .spec.pretty_size }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.system_disk_nvme_id" }}
{{- $diskName := (include "talm.discovered.system_disk_name" .) }}
{{- $diskStablePath := "" }}
{{- range (lookup "disks" "" "").items }}
{{- if and (eq .spec.dev_path $diskName) (eq .spec.transport "nvme") .spec.wwid }}
{{- $diskStablePath = (printf "/dev/disk/by-id/nvme-%s" .spec.wwid) }}
{{- break }}
{{- end }}
{{- end }}
{{- if $diskStablePath }}
{{- $diskStablePath }}
{{- else }}
{{- $diskName }} # Unable to determine a stable NVMe disk path, falling back to the disk name
{{- end }}
{{- end }}

{{- define "talm.discovered.default_addresses" }}
{{- with (lookup "nodeaddress" "" "default") }}
{{- toJson .spec.addresses }}
{{- end }}
{{- end }}

{{- /* JSON list of IPv4 addresses on the link carrying the IPv4
       default route. Filters routes to family=inet4 because consumers
       (cozystack and generic chart helpers) pair the returned addresses
       with a hardcoded IPv4 destination route — selecting the first
       default route regardless of family on a dual-stack node would
       cascade into the IPv6 family being applied to the address filter,
       and the node's IPv4 addresses would silently disappear from the
       rendered config. Mirrors gateway_by_link's IPv4-only convention. */ -}}
{{- define "talm.discovered.default_addresses_by_gateway" }}
{{- $linkName := "" }}
{{- $family := "" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- $linkName = .spec.outLinkName }}
{{- $family = .spec.family }}
{{- break }}
{{- end }}
{{- end }}
{{- /* Coerce .Values.floatingIP through toString before the prefix
       compare so an unquoted numeric YAML scalar (operator writes
       `floatingIP: 192168`) does not emit `%!s(int=192168)/` that
       never matches a real CIDR. Same trap the v1.12 multi-doc
       path guards against; legacy schema needs the same treatment.
       toString'd nil renders as "<nil>" which is also harmless —
       it cannot match a real CIDR prefix. */ -}}
{{- $fipStr := $.Values.floatingIP | toString }}
{{- $addresses := list }}
{{- /* Drop the same kernel-managed scopes addresses_by_link
       rejects (host loopback, link-local, "nowhere"). Real Talos
       COSI always sets scope=link for the 169.254/16 link-local
       range, so a legacy v1.11 render that filtered only the
       "host" scope was at risk of leaking link-local addresses
       verbatim into machine.network.interfaces[].addresses on
       the next COSI schema bump. Mirror the two helpers so a
       future bump that produces new link-local entries on the
       default-gateway-bearing link can't slip through one path
       while being correctly rejected by the other. */ -}}
{{- $skipScopes := list "host" "link" "nowhere" }}
{{- range (lookup "addresses" "" "").items }}
{{- /* Filter malformed or future-format entries the same way
       addresses_by_link does (cidrPrefixLen >= 0). A corrupt entry
       in the COSI addresses table must not leak verbatim into the
       legacy v1.11 machine.network.interfaces[].addresses block. */ -}}
{{- $address := .spec.address | toString }}
{{- $validCidr := ge (cidrPrefixLen $address) 0 }}
{{- if and (eq .spec.linkName $linkName) (eq .spec.family $family) (not (has (.spec.scope | toString) $skipScopes)) $validCidr }}
{{- if not (hasPrefix (printf "%s/" $fipStr) $address) }}
{{- $addresses = append $addresses $address }}
{{- end }}
{{- end }}
{{- end }}
{{- toJson $addresses }}
{{- end }}

{{- define "talm.discovered.physical_links_info" }}
# -- Discovered interfaces:
{{- range (lookup "links" "" "").items }}
{{- if and .spec.busPath (regexMatch "^(eno|eth|enp|enx|ens)" (.metadata.id | toString)) }}
# {{ .metadata.id }}:
#   hardwareAddr:{{ .spec.hardwareAddr }}
#   busPath: {{ .spec.busPath }}
#   driver: {{ .spec.driver }}
#   vendor: {{ .spec.vendor }}
#   product: {{ .spec.product }})
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_link_name" }}
{{- range (lookup "addresses" "" "").items }}
{{- if has .spec.address (fromJsonArray (include "talm.discovered.default_addresses" .)) }}
{{- .spec.linkName }}
{{- end }}
{{- end }}
{{- end }}

{{- /* All four default_link_*_by_gateway helpers below are IPv4-only.
       They identify the link that carries the chart's primary uplink, and
       that uplink is the same one default_gateway / default_addresses_by_gateway
       configure — selecting a different link here would produce a config
       where LinkConfig.name attaches to one NIC while LinkConfig.routes /
       addresses describe a different NIC, leaving both unconfigured.
       Picking the IPv4 default route's outLinkName keeps the whole
       chain pointed at the same NIC on multi-NIC dual-stack nodes
       (typical Hetzner shape: management NIC on IPv4, public NIC on
       IPv6, default routes on different links). Symmetric with
       gateway_by_link / default_gateway / default_addresses_by_gateway. */ -}}
{{- define "talm.discovered.default_link_name_by_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- .spec.outLinkName }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_link_address_by_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- (lookup "links" "" .spec.outLinkName).spec.hardwareAddr }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_link_bus_by_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- (lookup "links" "" .spec.outLinkName).spec.busPath }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_link_selector_by_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- with (lookup "links" "" .spec.outLinkName) }}
busPath: {{ .spec.busPath }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.predictable_link_name" -}}
{{ printf "enx%s" (lookup "links" "" . | dig "spec" "hardwareAddr" . | replace ":" "") }}
{{- end }}

{{- /* Scalar IPv4 default-route gateway (dst="", main table, family=inet4).
       Empty if the node has no IPv4 default route. IPv4-only by convention
       so the helper stays symmetric with gateway_by_link and so consumers
       that pair the returned gateway with an IPv4 destination
       (`network: 0.0.0.0/0` on the legacy schema, or no `network:` field
       on the typed RouteConfig schema) never end up with a malformed
       IPv4-dst + IPv6-gateway route on a dual-stack node. Talos derives
       the route family from the gateway literal at validation time, so a
       RouteConfig with gateway `fe80::1` and no `network:` field is
       rejected outright — silently breaking Layer2 VIP and any other
       feature that depends on the chart-emitted route entry. */ -}}
{{- define "talm.discovered.default_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- .spec.gateway }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_resolvers" }}
{{- with (lookup "resolvers" "" "resolvers") }}
{{- toJson .spec.dnsServers }}
{{- end }}
{{- end }}

{{- define "talm.discovered.existing_interfaces_configuration" }}
{{- with (lookup "machineconfig" "" "v1alpha1") }}
{{- $spec := .spec }}
{{- $interfaces := list }}
{{- if kindIs "string" $spec }}
{{- $interfaces = $spec | fromYaml | dig "machine" "network" "interfaces" (list) }}
{{- else }}
{{- $interfaces = $spec | dig "machine" "network" "interfaces" (list) }}
{{- end }}
{{- if $interfaces }}
{{- $interfaces | toYaml }}
{{- end }}
{{- end }}
{{- end }}

{{- /* Get bond slave interfaces for a given bond index */ -}}
{{- define "talm.discovered.bond_slaves" -}}
{{- $bondIndex := . -}}
{{- $slaves := list -}}
{{- range (lookup "links" "" "").items -}}
{{- if and (eq .spec.slaveKind "bond") (eq (int .spec.masterIndex) (int $bondIndex)) -}}
{{- $slaves = append $slaves .metadata.id -}}
{{- end -}}
{{- end -}}
{{- toJson $slaves -}}
{{- end -}}

{{- /* Get bridge member interfaces (ports) for a given bridge index.
       Discovered via spec.slaveKind=="bridge" + spec.masterIndex
       matching — symmetric to bond_slaves above. Returns the JSON list
       so the multi-doc renderer can iterate without reaching back into
       the links collection. */ -}}
{{- define "talm.discovered.bridge_slaves" -}}
{{- $bridgeIndex := . -}}
{{- $slaves := list -}}
{{- range (lookup "links" "" "").items -}}
{{- if and (eq .spec.slaveKind "bridge") (eq (int .spec.masterIndex) (int $bridgeIndex)) -}}
{{- $slaves = append $slaves .metadata.id -}}
{{- end -}}
{{- end -}}
{{- toJson $slaves -}}
{{- end -}}

{{- /* Generate bond configuration from bondMaster spec */ -}}
{{- define "talm.discovered.bond_config" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link (eq $link.spec.kind "bond") -}}
{{- $bondMaster := $link.spec.bondMaster -}}
{{- $slaves := fromJsonArray (include "talm.discovered.bond_slaves" $link.spec.index) -}}
bond:
  interfaces:
    {{- range $slaves }}
    - {{ . }}
    {{- end }}
  mode: {{ $bondMaster.mode }}
  {{- if $bondMaster.xmitHashPolicy }}
  xmitHashPolicy: {{ $bondMaster.xmitHashPolicy }}
  {{- end }}
  {{- if $bondMaster.lacpRate }}
  lacpRate: {{ $bondMaster.lacpRate }}
  {{- end }}
  {{- if $bondMaster.miimon }}
  miimon: {{ $bondMaster.miimon }}
  {{- end }}
  {{- if $bondMaster.updelay }}
  updelay: {{ $bondMaster.updelay }}
  {{- end }}
  {{- if $bondMaster.downdelay }}
  downdelay: {{ $bondMaster.downdelay }}
  {{- end }}
{{- end -}}
{{- end -}}

{{- /* Check if a link is a bond interface */ -}}
{{- define "talm.discovered.is_bond" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link (eq $link.spec.kind "bond") -}}
true
{{- end -}}
{{- end -}}

{{- /* Returns the link name whose discovered addresses contain a CIDR
       encompassing the supplied IP literal. Used by the multi-doc
       Layer2VIPConfig path to pin the VIP onto the link carrying the
       relevant subnet, rather than the IPv4 default-route link (which
       is wrong whenever the floatingIP lives on a non-default-route
       NIC, e.g. a private VLAN child on a Hetzner-style topology).
       Returns the empty string when no link's addresses contain the
       IP — the caller (multi-doc Layer2VIPConfig block in the
       cozystack and generic charts) falls back to
       default_link_name_by_gateway in that case.

       Selection rules:

         1. The link must be in the configurable-link set
            (talm.discovered.configurable_link_names) — addresses on
            links the chart does not emit a per-link document for
            (Wireguard, kernel-managed loopback, slave NICs of a
            bond, anything outside the {physical NIC, bond, vlan,
            bridge} set) must not steal the VIP. A VIP pinned there
            would have no surrounding network document.

         2. The address must be globally scoped — host-local,
            link-local, and nowhere-scoped addresses are skipped, the
            same filter addresses_by_link applies before emitting
            LinkConfig.addresses.

         3. Longest-prefix wins. When a node has overlapping subnets
            (e.g. a /16 on a physical NIC and a /24 on a VLAN child
            both containing the floatingIP), the more specific subnet
            is the right answer — same rule the kernel uses for route
            decisions. Without this, iteration order would silently
            decide.

       CIDR-membership is computed by the engine-registered
       cidrContains helper (net/netip-backed); chart templates do not
       have to do per-family bit math, and IPv4 / IPv6 are handled
       uniformly. cidrContains is lenient on parse failures (returns
       false), so a single corrupt or future-format entry in the
       address table cannot crash the entire render. */ -}}
{{- define "talm.discovered.link_name_for_address" -}}
{{- $target := . -}}
{{- /* configurable_link_names ignores its dot input — it walks the
       links collection via lookup. Any value is safe; passing
       $target rather than synthesizing a new dot here keeps the
       define body uncluttered. */ -}}
{{- $configurable := fromJsonArray (include "talm.discovered.configurable_link_names" $target) -}}
{{- /* Hoist the scope skip-list out of the range body so it is
       built once per call rather than once per address-table
       entry. */ -}}
{{- $skipScopes := list "host" "link" "nowhere" -}}
{{- /* Track best match across iterations. dict-mutation via Sprig
       set is the established pattern for cross-iteration state in
       Go templates; range introduces a new scope per iteration so
       a plain $var = ... reassignment does not propagate. */ -}}
{{- $best := dict "link" "" "prefixLen" -1 -}}
{{- range (lookup "addresses" "" "").items -}}
{{- $address := .spec.address | toString -}}
{{- $linkName := .spec.linkName | toString -}}
{{- if and $address $linkName -}}
{{- /* Filter 1: link must be configurable. */ -}}
{{- if has $linkName $configurable -}}
{{- /* Filter 2: scope must be set and not host/link/nowhere.
       Match the addresses_by_link rule exactly: truthy check on
       the raw .spec.scope field (rejects nil) AND non-empty
       string check on its toString'd value AND not in the
       skip-list. The looser variant (only the toString'd check)
       would let a nil-scope entry through as the literal
       "<nil>" string, which is neither "" nor in the skip set.
       Real Talos COSI always sets scope, so this is a latent
       guardrail rather than a hot path. */ -}}
{{- if and .spec.scope (ne (.spec.scope | toString) "") (not (has (.spec.scope | toString) $skipScopes)) -}}
{{- /* Filter 3: CIDR must contain the target. */ -}}
{{- if cidrContains $address $target -}}
{{- /* Filter 4: longest-prefix match. cidrPrefixLen is the
       engine-registered helper that wraps net/netip.Prefix.Bits;
       it returns -1 on parse failure, which loses to any valid
       prefix length under `gt`. The prior shape split the CIDR on
       "/" and atoi-d the second part — masked the failure mode
       where a /0 default-route entry mixed into the address table
       would tie at 0 and let iteration order pick the winner.
       Ties at the same prefix length resolve by COSI's emission
       order for the addresses resource — rare in practice (two
       configurable links with identically-sized CIDRs both
       containing the floatingIP). */ -}}
{{- $prefixLen := cidrPrefixLen $address -}}
{{- if gt $prefixLen (get $best "prefixLen") -}}
{{- $_ := set $best "link" $linkName -}}
{{- $_ := set $best "prefixLen" $prefixLen -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- get $best "link" -}}
{{- end -}}

{{- /* Check if a link is a vlan interface */ -}}
{{- define "talm.discovered.is_vlan" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link (eq $link.spec.kind "vlan") -}}
true
{{- end -}}
{{- end -}}

{{- /* Get parent link name by linkIndex */ -}}
{{- define "talm.discovered.parent_link_name" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link $link.spec.linkIndex -}}
{{- $parentIndex := $link.spec.linkIndex -}}
{{- range (lookup "links" "" "").items -}}
{{- if eq (int .spec.index) (int $parentIndex) -}}
{{- .metadata.id -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- /* Get vlan ID from link */ -}}
{{- define "talm.discovered.vlan_id" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link $link.spec.vlan -}}
{{- $link.spec.vlan.vlanID -}}
{{- end -}}
{{- end -}}

{{- /* Generate vlan configuration */ -}}
{{- define "talm.discovered.vlan_config" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link (eq $link.spec.kind "vlan") -}}
vlans:
  - vlanId: {{ $link.spec.vlan.vlanID }}
{{- end -}}
{{- end -}}

{{- /*
  Multi-NIC discovery helpers (#125).

  The `default_*_by_gateway` family above resolves only the link carrying the
  default route (primary). Templates targeting nodes with secondary NICs
  (storage links on a control-plane, second uplink, etc.) need to enumerate
  every physical link and read its addresses/routes/MAC by name. The helpers
  below are the by-name building blocks; existing default_*_by_gateway helpers
  remain wrappers that resolve the primary link and call into these.
*/ -}}

{{- /* JSON list of physical link names (raw NICs only — not bond/vlan masters).
       Renamed from `physical_links` to avoid collision with the older
       `physical_links_info` helper, which renders YAML comments.
       Bond slaves are NOT filtered by this helper — callers that need to
       skip slaves (e.g. the multi-doc renderer that already emits the
       master's BondConfig) must filter on spec.slaveKind themselves, or
       use configurable_link_names below which already filters them. */ -}}
{{- define "talm.discovered.physical_link_names" -}}
{{- $names := list -}}
{{- range (lookup "links" "" "").items -}}
{{- if and .spec.busPath (regexMatch "^(eno|eth|enp|enx|ens)" (.metadata.id | toString)) -}}
{{- $names = append $names .metadata.id -}}
{{- end -}}
{{- end -}}
{{- toJson $names -}}
{{- end -}}

{{- /* JSON list of every link a user template can configure: physical NICs
       plus bond / vlan / bridge top-level links. Bond slaves (physical NICs
       enrolled into a bond master) are excluded — emitting a standalone
       LinkConfig for a slave alongside the master's BondConfig produces
       conflicting declarations Talos will reject during controller
       convergence. The slave-membership fact comes from spec.slaveKind
       (set by the link controller when a physical NIC is attached to a
       bond / bridge / team), so filtering on it covers slaves regardless
       of whether the master is bond, bridge, or future kinds. */ -}}
{{- define "talm.discovered.configurable_link_names" -}}
{{- $names := list -}}
{{- range (lookup "links" "" "").items -}}
{{- $isPhysical := and .spec.busPath (regexMatch "^(eno|eth|enp|enx|ens)" (.metadata.id | toString)) -}}
{{- $isVirtual := has (.spec.kind | toString) (list "bond" "vlan" "bridge") -}}
{{- $isSlave := and .spec.slaveKind (ne (.spec.slaveKind | toString) "") -}}
{{- if and (or $isPhysical $isVirtual) (not $isSlave) -}}
{{- $names = append $names .metadata.id -}}
{{- end -}}
{{- end -}}
{{- toJson $names -}}
{{- end -}}

{{- /* JSON list of CIDR addresses configured on the given link, excluding
       kernel-managed scopes (host loopback, link-local, nowhere) and
       addresses with no scope set at all. Both IPv4 and IPv6 globally-
       scoped addresses are returned — chart consumers (cozystack /
       generic multi-doc renderer) emit them verbatim into LinkConfig /
       VLANConfig / BondConfig.addresses, dropping the operator-declared
       floatingIP via an inline filter to keep the leader's transient VIP
       out of the static config. Add a per-family helper if a future
       caller needs IPv4- or IPv6-only output rather than tightening this
       one. */ -}}
{{- define "talm.discovered.addresses_by_link" -}}
{{- $linkName := . -}}
{{- $addresses := list -}}
{{- /* Hoist the scope skip-list out of the range body so it is
       built once per call rather than once per address-table
       entry. Symmetric to the hoisted skip-list inside
       link_name_for_address. */ -}}
{{- $skipScopes := list "host" "link" "nowhere" -}}
{{- range (lookup "addresses" "" "").items -}}
{{- $hasScope := and .spec.scope (ne (.spec.scope | toString) "") -}}
{{- $skip := has (.spec.scope | toString) $skipScopes -}}
{{- /* Filter out corrupt or future-format entries whose address
       does not parse as a CIDR. cidrPrefixLen returns -1 on parse
       failure, which we treat as "skip" the same way
       link_name_for_address does — a single bad entry in COSI
       must not propagate into LinkConfig / VLANConfig / BridgeConfig
       addresses where it would produce a config Talos rejects on
       apply with a less-informative error than the chart could
       give. */ -}}
{{- $address := .spec.address | toString -}}
{{- $validCidr := ge (cidrPrefixLen $address) 0 -}}
{{- if and (eq .spec.linkName $linkName) $hasScope (not $skip) $validCidr -}}
{{- $addresses = append $addresses $address -}}
{{- end -}}
{{- end -}}
{{- toJson $addresses -}}
{{- end -}}

{{- /* Scalar IPv4 gateway for the default route (dst="", main table) on the
       given link. Empty if the link has no IPv4 default route. IPv4-only by
       convention to avoid family/address mismatch on dual-stack nodes — add
       a sibling helper for IPv6 if you need it. */ -}}
{{- define "talm.discovered.gateway_by_link" -}}
{{- $linkName := . -}}
{{- range (lookup "routes" "" "").items -}}
{{- if and (eq .spec.outLinkName $linkName) (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") -}}
{{- .spec.gateway -}}
{{- break -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- /* JSON list of non-default routes on the given link, across all
       routing tables (the `table` field is included so callers can
       filter — gateway_by_link narrows to table=main, this helper does
       not). Each entry is a flat map {dst, gateway, family, table,
       priority} so consumers can fromJsonArray + range + dig. Absent
       fields are emitted as empty strings; present fields including the
       integer 0 (e.g. priority: 0) round-trip through toString. */ -}}
{{- define "talm.discovered.routes_by_link" -}}
{{- $linkName := . -}}
{{- $routes := list -}}
{{- range (lookup "routes" "" "").items -}}
{{- if and (eq .spec.outLinkName $linkName) (not (eq .spec.dst "")) -}}
{{- $gateway := "" -}}
{{- if not (kindIs "invalid" .spec.gateway) -}}{{- $gateway = printf "%v" .spec.gateway -}}{{- end -}}
{{- $family := "" -}}
{{- if not (kindIs "invalid" .spec.family) -}}{{- $family = printf "%v" .spec.family -}}{{- end -}}
{{- $table := "" -}}
{{- if not (kindIs "invalid" .spec.table) -}}{{- $table = printf "%v" .spec.table -}}{{- end -}}
{{- $priority := "" -}}
{{- if not (kindIs "invalid" .spec.priority) -}}{{- $priority = printf "%v" .spec.priority -}}{{- end -}}
{{- $entry := dict "dst" .spec.dst "gateway" $gateway "family" $family "table" $table "priority" $priority -}}
{{- $routes = append $routes $entry -}}
{{- end -}}
{{- end -}}
{{- toJson $routes -}}
{{- end -}}

{{- /* Scalar MAC address for the given link, or empty if the link is
       missing or has no hardwareAddr (virtual links have spec but may
       lack the field; test mocks may return {} for unknown ids). The
       field guard prevents `nil | toString` from rendering "<nil>". */ -}}
{{- define "talm.discovered.mac_by_link" -}}
{{- $link := lookup "links" "" . -}}
{{- if and $link $link.spec $link.spec.hardwareAddr -}}
{{- $link.spec.hardwareAddr | toString -}}
{{- end -}}
{{- end -}}

{{- /* Scalar PCI / bus path for the given link, or empty if the link is
       missing or has no busPath (virtual links such as bonds expose a
       spec without a busPath). The field guard prevents
       `nil | toString` from rendering "<nil>". */ -}}
{{- define "talm.discovered.bus_by_link" -}}
{{- $link := lookup "links" "" . -}}
{{- if and $link $link.spec $link.spec.busPath -}}
{{- $link.spec.busPath | toString -}}
{{- end -}}
{{- end -}}

{{- /* YAML fragment `busPath: <path>` for use as a Talos deviceSelector by
       link name. Prefer this over emitting `interface:` when you need the
       config to be portable across renames (e.g. predictable network names). */ -}}
{{- define "talm.discovered.link_selector_by_name" -}}
{{- $link := lookup "links" "" . -}}
{{- if and $link $link.spec.busPath -}}
busPath: {{ $link.spec.busPath }}
{{- end -}}
{{- end -}}

{{- /* Validate that a value is a well-formed DNS-1123 subdomain
       (RFC 1035 syntax + RFC 1123 leading-digit relaxation). On
       success returns the value verbatim so callers can pipe it
       into `quote` or use it inline. On any violation fails the
       render with a precise message naming the field and the
       offending value.

       Mirrors what k8s.io/apimachinery/pkg/util/validation
       .IsDNS1123Subdomain enforces in Go-side flag validation
       (talm init --name) so chart-rendered values agree with
       values an operator passes through the CLI:

         1. non-empty
         2. total length <= 253 chars
         3. matches RFC 1123 subdomain regex (lowercase, only
            [a-z0-9-.], each label starts/ends with [a-z0-9],
            no double dots)

       Per-label length (63 chars) is NOT enforced — upstream
       IsDNS1123Subdomain does not enforce it either, and there
       is no Talos-side cluster-name length cap that aligns with
       a 63-char floor. Stay symmetric with Go-side validation.

       Coercion: .value is rendered through `printf "%v"` before
       length / regex checks so an unquoted numeric YAML scalar
       (e.g. `clusterName: 123`) becomes the string "123" instead
       of crashing the template at `len of type int`. The eq-""
       emptiness check also avoids treating numeric 0 as falsy.

       Usage:
           {{ include "talm.validate.dns1123subdomain"
              (dict "value" .Values.clusterName "field" "clusterName") }}
       */ -}}
{{- define "talm.validate.dns1123subdomain" -}}
{{- $field := .field -}}
{{- $value := printf "%v" .value -}}
{{- if eq $value "" -}}
{{- fail (printf "values.yaml: %s must be a non-empty DNS-1123 subdomain (must be lowercase, only [a-z0-9-.], start and end with [a-z0-9], max 253 chars)" $field) -}}
{{- end -}}
{{- if gt (len $value) 253 -}}
{{- fail (printf "values.yaml: %s=%q exceeds 253 characters (DNS-1123 subdomain length limit)" $field $value) -}}
{{- end -}}
{{- if not (regexMatch "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$" $value) -}}
{{- fail (printf "values.yaml: %s=%q is not a valid DNS-1123 subdomain (must be lowercase, only [a-z0-9-.], start and end with [a-z0-9])" $field $value) -}}
{{- end -}}
{{- $value -}}
{{- end -}}

{{- /* talm.config.network.multidoc reconstructs the v1.12+ multi-doc
       network config from discovery resources. Single source of truth
       used by both the cozystack and generic chart presets — each
       chart's talos.config.network.multidoc forwards here via include.
       Lives in the talm library chart because both charts include
       talm as a subchart for discovery helpers, so the define is in
       scope under one canonical name. */ -}}
{{- define "talm.config.network.multidoc" }}
{{- /* Multi-doc format reconstructs network config from discovery resources.
       Every configurable link on the node (physical NIC, bond, VLAN, bridge)
       gets its own document so a multi-NIC node ends up with all NICs
       configured rather than only the gateway-bearing one. The gateway-
       link's IPv4 default-route gateway is emitted only on that link's
       document; every other link gets its addresses without a default route.
       MTU is surfaced when discovery reports a value so non-default-MTU
       links (jumbo frames, GRE) survive a re-render.

       existing_interfaces_configuration is not consulted here: v1.12 nodes
       store network config in separate documents (LinkConfig, BondConfig,
       VLANConfig), not in the legacy machine.network.interfaces field. The
       guardrail below catches the upgrade case where a node was originally
       bootstrapped on a chart that emitted the legacy schema and still
       carries non-empty machine.network.interfaces[] in its running
       MachineConfig — the renderer cannot translate those entries today
       and would otherwise silently drop them on the next apply. */ -}}
{{- $legacyInterfaces := include "talm.discovered.existing_interfaces_configuration" . }}
{{- if $legacyInterfaces }}
{{- fail (printf "talm: the multi-doc renderer cannot translate legacy machine.network.interfaces[] from the running MachineConfig. Move the interfaces, vlans, and addresses below into per-node body overlays as v1.12 typed documents (LinkConfig, VLANConfig, BondConfig, RouteConfig) before re-running talm apply, or pin templateOptions.talosVersion to v1.11 in Chart.yaml until the translator lands.\n\nDetected legacy block:\n%s" $legacyInterfaces) }}
{{- end }}
{{- (include "talm.discovered.physical_links_info" .) }}
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: {{ include "talm.discovered.hostname" . | quote }}
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
{{- $resolvers := include "talm.discovered.default_resolvers" . }}
{{- if $resolvers }}
{{- range fromJsonArray $resolvers }}
  - address: {{ . | quote }}
{{- end }}
{{- else }}
  []
{{- end }}
{{- /* Coerce .Values.floatingIP to its string form once at the
       top of the multi-doc body and reuse the result everywhere
       a downstream lookup or formatter needs it. The per-link
       addresses_by_link strip on every link emission below
       depends on the same stringified value — a worker render
       with `floatingIP: 192168` would otherwise feed printf
       "%s/" an int, producing `%!s(int=192168)/` that never
       matches a CIDR. The coercion isolates that trap to one
       place and lets the rest of the template treat the value
       uniformly.

       "<nil>" is Sprig's serialisation of nil and "" is the
       unset string; both mean "operator did not supply a
       value". The shared talm.validate_floatingIP partial below
       handles the actual fail-fast — invoke it here AND in the
       legacy define so a malformed value fails at render time
       regardless of the rendered Talos version. */}}
{{- $fipStr := .Values.floatingIP | toString }}
{{- $fipIsSet := and (ne $fipStr "") (ne $fipStr "<nil>") }}
{{- include "talm.validate_floatingIP" . }}
{{- /* Operator-declared vipLink override: emit Layer2VIPConfig
       regardless of discovery state. Useful when the target link
       does not yet exist on the live system at first apply (typical
       case: a VLAN sub-interface this template is about to bring up).
       The discovery-derived block below skips its own Layer2VIPConfig
       when this branch fires, so we never emit duplicates. */}}
{{- if and $fipIsSet .Values.vipLink (eq .MachineType "controlplane") }}
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: {{ $fipStr | quote }}
link: {{ .Values.vipLink }}
{{- end }}
{{- $defaultLinkName := include "talm.discovered.default_link_name_by_gateway" . }}
{{- $configurableLinks := fromJsonArray (include "talm.discovered.configurable_link_names" .) }}
{{- range $linkName := $configurableLinks }}
{{- $link := lookup "links" "" $linkName }}
{{- if $link }}
{{- $kind := $link.spec.kind | toString }}
{{- $isGatewayLink := eq $linkName $defaultLinkName }}
{{- $rawAddresses := fromJsonArray (include "talm.discovered.addresses_by_link" $linkName) }}
{{- /* Strip the operator-declared floatingIP from per-link addresses
       so the VIP currently held by this leader does not leak into
       LinkConfig.addresses. Talos's VIP operator installs the VIP
       as a regular global-scope address indistinguishable from a
       permanent one in COSI; without the filter, a re-render against
       the VIP-active node would declare the VIP both as a permanent
       address and as the Layer2VIPConfig target, putting the leader
       and follower configs out of sync. */}}
{{- $addresses := list }}
{{- range $rawAddresses }}
{{- /* Use the hoisted $fipStr/$fipIsSet from the top of the
       define so the strip honours the same coerced value the
       validation block above used. Going through `printf "%s/"
       $.Values.floatingIP` directly would emit
       `%!s(int=192168)/` for a numeric YAML scalar on a worker
       render (controlplane was caught by the fail-fast). */ -}}
{{- if not (and $fipIsSet (hasPrefix (printf "%s/" $fipStr) .)) }}
{{- $addresses = append $addresses . }}
{{- end }}
{{- end }}
{{- $linkGateway := "" }}
{{- if $isGatewayLink }}
{{- $linkGateway = include "talm.discovered.gateway_by_link" $linkName }}
{{- end }}
{{- if eq $kind "bridge" }}
{{- /* BridgeConfig emission. Discovers bridge ports (members) via
       talm.discovered.bridge_slaves and emits a typed v1.12+
       BridgeConfig document with the same address / route / mtu
       shape as the other branches. STP and VLAN filtering are
       opt-in: they are emitted only when the bridge controller
       reported a non-nil spec.bridgeMaster.stp / spec.bridgeMaster
       value, so a default-state bridge stays minimal. */ -}}
{{- $bridgeMaster := $link.spec.bridgeMaster }}
{{- $bridgePorts := fromJsonArray (include "talm.discovered.bridge_slaves" $link.spec.index) }}
---
apiVersion: v1alpha1
kind: BridgeConfig
name: {{ $linkName }}
{{- if $bridgePorts }}
links:
{{- range $bridgePorts }}
  - {{ . }}
{{- end }}
{{- end }}
{{- if $bridgeMaster }}
{{- if $bridgeMaster.stp }}
{{- if hasKey $bridgeMaster.stp "enabled" }}
stp:
  enabled: {{ $bridgeMaster.stp.enabled }}
{{- end }}
{{- end }}
{{- /* COSI's BridgeVLANSpec serialises FilteringEnabled as
       yaml:"filteringEnabled" (verified against
       siderolabs/talos pkg/machinery/resources/network/link.go).
       The output-side BridgeConfig schema uses the shorter
       yaml:"filtering,omitempty" key — so we read the long form
       from discovery and emit the short form into the rendered
       document. */ -}}
{{- if $bridgeMaster.vlan }}
{{- if hasKey $bridgeMaster.vlan "filteringEnabled" }}
vlan:
  filtering: {{ $bridgeMaster.vlan.filteringEnabled }}
{{- end }}
{{- end }}
{{- end }}
{{- if $addresses }}
addresses:
{{- range $addresses }}
  - address: {{ . }}
{{- end }}
{{- end }}
{{- if $linkGateway }}
routes:
  - gateway: {{ $linkGateway }}
{{- end }}
{{- if $link.spec.mtu }}
mtu: {{ $link.spec.mtu }}
{{- end }}
{{- else if eq $kind "bond" }}
{{- $bondMaster := $link.spec.bondMaster }}
{{- $slaves := fromJsonArray (include "talm.discovered.bond_slaves" $link.spec.index) }}
{{- if not $slaves }}
{{- /* Talos's link controller can auto-create a bond stub in COSI
       link state before any operator configuration enslaves
       physical NICs to it: the master link carries a bondMaster
       spec but no other link has slaveKind: bond + masterIndex
       pointing at it. Emitting BondConfig with empty `links:`
       produces a document Talos rejects on apply ("at least one
       link must be specified"). Treat empty-slaves as not-a-
       user-bond and skip the document. An operator who intends
       a bond must declare its slaves via a per-node body overlay;
       until then the discovered stub is not promoted to config. */ -}}
{{- else }}
---
apiVersion: v1alpha1
kind: BondConfig
name: {{ $linkName }}
links:
{{- range $slaves }}
  - {{ . }}
{{- end }}
{{- if $bondMaster }}
{{- if $bondMaster.mode }}
bondMode: {{ $bondMaster.mode }}
{{- end }}
{{- if $bondMaster.xmitHashPolicy }}
xmitHashPolicy: {{ $bondMaster.xmitHashPolicy }}
{{- end }}
{{- if $bondMaster.lacpRate }}
lacpRate: {{ $bondMaster.lacpRate }}
{{- end }}
{{- if $bondMaster.miimon }}
miimon: {{ $bondMaster.miimon }}
{{- end }}
{{- if $bondMaster.updelay }}
updelay: {{ $bondMaster.updelay }}
{{- end }}
{{- if $bondMaster.downdelay }}
downdelay: {{ $bondMaster.downdelay }}
{{- end }}
{{- end }}
{{- if $addresses }}
addresses:
{{- range $addresses }}
  - address: {{ . }}
{{- end }}
{{- end }}
{{- if $linkGateway }}
routes:
  - gateway: {{ $linkGateway }}
{{- end }}
{{- if $link.spec.mtu }}
mtu: {{ $link.spec.mtu }}
{{- end }}
{{- end }}
{{- else if eq $kind "vlan" }}
{{- $parentLinkName := include "talm.discovered.parent_link_name" $linkName }}
{{- $vlanID := include "talm.discovered.vlan_id" $linkName }}
{{- if not $parentLinkName }}
{{- /* VLANConfig requires the parent field on the wire. Emitting one
       without it produces a document Talos rejects on apply. Treat the
       partial-discovery case as fail-fast — a VLAN with an unresolvable
       linkIndex is a discovery bug, not a config we can render. */ -}}
{{- fail (printf "talm: discovered VLAN %q has no resolvable parent link (spec.linkIndex points at a non-existent link). VLANConfig requires the parent field; refusing to emit an invalid document. Fix the discovery state or declare the VLAN explicitly via a per-node body overlay." $linkName) }}
{{- end }}
{{- if not $vlanID }}
{{- /* VLANConfig also requires vlanID. Symmetric guardrail to the
       missing-parent case above — discovery without spec.vlan.vlanID
       cannot produce a valid VLANConfig. */ -}}
{{- fail (printf "talm: discovered VLAN %q has no resolvable vlanID (spec.vlan.vlanID is unset). VLANConfig requires vlanID; refusing to emit an invalid document. Fix the discovery state or declare the VLAN explicitly via a per-node body overlay." $linkName) }}
{{- end }}
---
apiVersion: v1alpha1
kind: VLANConfig
name: {{ $linkName }}
vlanID: {{ $vlanID }}
parent: {{ $parentLinkName }}
{{- if $addresses }}
addresses:
{{- range $addresses }}
  - address: {{ . }}
{{- end }}
{{- end }}
{{- if $linkGateway }}
routes:
  - gateway: {{ $linkGateway }}
{{- end }}
{{- if $link.spec.mtu }}
mtu: {{ $link.spec.mtu }}
{{- end }}
{{- else }}
---
apiVersion: v1alpha1
kind: LinkConfig
name: {{ $linkName }}
{{- if $addresses }}
addresses:
{{- range $addresses }}
  - address: {{ . }}
{{- end }}
{{- end }}
{{- if $linkGateway }}
routes:
  - gateway: {{ $linkGateway }}
{{- end }}
{{- if $link.spec.mtu }}
mtu: {{ $link.spec.mtu }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- /* Discovery-derived Layer2VIPConfig: skipped when the operator
       has set .Values.vipLink, since the override-path block above
       has already emitted the document with the operator's chosen
       link.

       Link selection prefers the link whose discovered addresses
       contain the floatingIP (talm.discovered.link_name_for_address),
       so a VIP in a private subnet hosted on a VLAN child lands on
       that VLAN — not on the IPv4-default-route NIC. The
       default-gateway link stays as the fallback for topologies
       where the VIP isn't on any discovered subnet (typical for
       upstream-routable VIPs that arrive via the default-route
       link). When neither resolves a link, no Layer2VIPConfig is
       emitted, matching the prior behaviour. */}}
{{- if and $fipIsSet (not .Values.vipLink) (eq .MachineType "controlplane") }}
{{- $vipLink := include "talm.discovered.link_name_for_address" $fipStr }}
{{- /* Default-gateway fallback must also point at a configurable
       link — otherwise an unmanaged default-route NIC (Wireguard,
       a slave NIC of a bond, anything outside the configurable
       set) would silently win selection and the rendered
       Layer2VIPConfig would dangle on a link the chart never
       emits a per-link document for. Mirror the same
       configurable-link gate link_name_for_address applies inside
       its own iteration. */ -}}
{{- if not $vipLink }}
{{- if has $defaultLinkName $configurableLinks }}
{{- $vipLink = $defaultLinkName }}
{{- end }}
{{- end }}
{{- if $vipLink }}
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: {{ $fipStr | quote }}
link: {{ $vipLink }}
{{- end }}
{{- end }}
{{- end }}
